CREATE TABLE IF NOT EXISTS sources (
  id INTEGER PRIMARY KEY, payload TEXT NOT NULL, fetched_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS conversions (
  cache_key TEXT PRIMARY KEY, payload TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS jobs (
  cache_key TEXT PRIMARY KEY, lease TEXT NOT NULL, expires_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS daily_budget (
  day TEXT PRIMARY KEY, attempts INTEGER NOT NULL
);
